### ISSUE TITLE
Improvement to the encryption flow

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#351]
- [x] support encrypting an entire dir.
- [ ] Add a unit test for encrypting a single model and for an entire dir.
- [x] Make --test default.
- [x] Add option --build_target to cross build like below.
- [x] let's use ./tmp.encrypt_model.Dockerfile so it's easier to execute only one.
- [ ] Why is sudo needed? IMO the Docker container should use the right permissions.
- [x] Generalize `_tweak_init`.
- [x] Pass the model name should be passed from command line.

**Comment by gpsaggese** [comment]
The branch with some TODOs is here
`CmTask351_Improvement_to_the_encryption_flow`

**Comment by KangmingL** [comment]
OK, I'm working on it. Trying to be familiar with the tasks and TODOs.

**Comment by KangmingL** [comment]
@samarth9008 For this TODO `# TODO(gp): Add a unit test for encrypting a single model and for an entire dir.
# We want to use hsystem.system() using 
# /Users/saggese/src/sorrentum1/dev_scripts/encrypt_model.py --model_dir dataflow_lemonade/pipelines/C5 -v DEBUG --test`
Is there any methods I can use to ignore all the outputs from Docker, so I can get model outputs only? Also is it possible to share with me more models so I can test encrypting entire dir.

**Comment by samarth9008** [comment]
@gpsaggese can answer it better.

**Comment by KangmingL** [comment]
@gpsaggese For this TODO
`
# TODO(gp): The model name should be passed from the command line.
    script = f'python -c "import {import_path}.C5a_pipeline as f; a = f.C5a_DagBuilder(); print(a)"'
`
is it guaranteed all models can be tested with `a = f.{model_name}_DagBuilder();print(a)`?

**Comment by gpsaggese** [comment]
Good questions.

1) together with --model_dir let's pass a --model_dag_builder which is used as the name of the dag builder `{model_name}()` (not `{model_name}_DagBuilder()`)
2) you can use `dataflow_amp/pipelines/` to encrypt all the models in one dir and use `--model_dag_builder Mock1_DagBuilder`
- If it works it should work also for other models in the same dir structure
3) you can use `hsystem.system_to_string()` and then manipulate the output in Python

**Comment by PomazkinG** [comment]
not sure to which EPIC it belongs, probably we need a separate EPIC for `dev scripts`, put it under `DEV_TOOLS` for now

**Comment by samarth9008** [comment]
@KangmingL How about you make a TODO list in the description of this issue and mark it as done one by one as you are done with it. Lets start with `supporting an dir`

You can refer to this doc to get an understanding of `docker buildx`

https://docs.docker.com/build/building/multi-platform/
https://docs.docker.com/engine/reference/commandline/buildx/

**Comment by KangmingL** [comment]
Sure, actually I'm almost done except for the tests.

**Comment by KangmingL** [comment]
- [ ] support encrypting an entire dir.
- [ ] Add a unit test for encrypting a single model and for an entire dir.
- [ ] Make --test default.
- [ ] Add option --build_target to cross build like below.
- [ ] let's use ./tmp.encrypt_model.Dockerfile so it's easier to execute only one.
- [ ] Why is sudo needed? IMO the Docker container should use the right permissions.
- [ ] Generalize `_tweak_init`.
- [ ] Pass the model name should be passed from command line.

**Comment by KangmingL** [comment]
@samarth9008 I'm a bit confused about writing test for an entire dir. There can be many models in a dir, and they may need different ways for testing. How it is possible for testing an entire dir without knowing what those models are? I feel like I didn't understand this TODO correctly or I'm missing some assumptions.

**Comment by gpsaggese** [comment]
1) let's keep pushing code often (personally I commit and push always together so my local client is in sync with the remote all the times)

2) we can do multiple PRs for the same issue, so you don't have to fix everything in one PR

3) Yes, in practice the testing is just calling the API that the script is using (this is better than using `hsystem.system` since in this way we measure coverage) and make sure that the encryption of the model works.
- I would do this in a separate PR, after everything else is done

Pls do small PRs / small interactions. Our goal is "1 PR per day", so that we can tell you if you are going in the right direction

Make sense?

**Comment by KangmingL** [comment]
Make sense to me, I will put testing part in another PR.

**Comment by samarth9008** [comment]
Closing as it is done.
