### ISSUE TITLE
DOCS - Publish documentation v0.1

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#64]
We can start from our coding conventions 

P1, Let's chat about it

**Comment by DanilYachmenev** [comment]
@gpsaggese

So, after discussion with @tamriq,

At first we need to understand:
1. What documents do we want to publish?
    - Select docs from [Gdrive](https://drive.google.com/drive/u/0/folders/1zawE6IEBDpWLTbpK-03z75f5pu_T9Jba)
    - Set order to split on PRs
2. Where do we want to publish the docs?
    - Should it be a Gdrive or a public Git repo?

We can keep chat about it here and then discuss closely on a Wed call if needed

**Comment by gpsaggese** [comment]
> > We can create a dir Sorrentum and move files one by one. But for each file there needs to be a process like:
> 
> @gpsaggese, all clear, but just to clarify - do you mean to create Sorrentum folder at Gdrive and gradually move reviewed and refined docs there, right?

Correct. We can save them here https://drive.google.com/drive/u/1/folders/1h5jKCiy_jHe2lAIF8HKK-Ah-_Va-xdXh

> 
> And actually we can convert this issue to an EPIC since it will take some time for sure and is very specific. However, I do not really see an option to do it in this repo

Yes, we don't have ZenHub here. I'm ok with just having a single issue (like this one) and then we work on one doc at the time (review, move, delete the old one using the checklist).

The important thing is to do one doc at the time (and not brutal move) and review it for correctness.

**Comment by DanilYachmenev** [comment]
At certain point let's agree on the next docs to publish, since some docs on the [Gdrive](https://drive.google.com/drive/u/0/folders/1sJDqCjM1Q_nq8diyZDiWO8mVBQW5Wg_X) are either not finished, or may be obsolete

For now I suggest to move the docs that are basically finished and contain useful basic info:
- [ ] [Git - Workflows and best practices](https://docs.google.com/document/d/1zahC8uDnFGYRSgkBrQRgg3W3ZmDjZZJj6yln6YeuHq4/edit#heading=h.c2cuxz4yki3)
- [ ] [GitHub / ZenHub workflows](https://docs.google.com/document/d/1M8weNOzMnS7vdMPzEyQ4g7OsCUXXsCn60qzPWsA7SlQ/edit#heading=h.usgoh8klm0ts)
- [ ] [Code review](https://docs.google.com/document/d/1DrulKZyvgdHPcXxblkO-uBtu_zTxD-rp476u1QPzGGc/edit#heading=h.6da73fq05ij1)
- [ ] [Documentation author guidelines](https://docs.google.com/document/d/1I_4sNeQTzFmAAsxWJS11vjb1wRtzHzgSXK8KTKkIx-o/edit#heading=h.n9r9ljnj6ch7)

wdyt?
I'll file the corresponding issues if approved

**Comment by gpsaggese** [comment]
We are deciding how to reorg the material here https://app.zenhub.com/workspaces/cm-615371012ed326001e044788/issues/gh/cryptokaizen/cmamp/4235

Let's converge on this first

**Comment by gpsaggese** [comment]
I've started with converting the gdoc to markdown

https://docs.google.com/document/d/1zahC8uDnFGYRSgkBrQRgg3W3ZmDjZZJj6yln6YeuHq4/edit#
to 
https://github.com/sorrentum/sorrentum/blob/master/docs/Git_workflow_and_best_practice.md

The conversion didn't work great, can you pls finish fixing the markdown manually?
We will add flows to lint it properly.

**Comment by gpsaggese** [comment]
- [ ] Convert to markdown https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk/edit

- [ ] Each markdown should have a one-line description in the master README with a link to the doc so that it's easier to navigate

**Comment by gpsaggese** [comment]
Yes pls, let's outsource the documentation conversion. So let's file two bugs and mark them as GFI.
@samarth9008 can assign them to students
